# Generated by Django 4.0.4 on 2022-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_carousel_alter_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='message',
            field=models.CharField(default='Banner Size must be 700X350 ', max_length=200),
        ),
    ]
