# Generated by Django 4.0.4 on 2022-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Time must be in 24 hour format', max_length=100)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
            ],
        ),
    ]
