# Generated by Django 4.0.4 on 2022-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0018_managecart_delete_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='studentId',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
