# Generated by Django 4.0.4 on 2022-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0020_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='stock',
            field=models.CharField(choices=[('YES', 'Available'), ('NO', 'Not Available')], default='NO', max_length=10),
        ),
    ]
