# Generated by Django 4.0.4 on 2022-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0021_items_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('delivered', 'Delivered')], default='Pending', max_length=10),
        ),
    ]
