# Generated by Django 4.1.6 on 2023-02-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0024_static'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Static',
        ),
    ]
