# Generated by Django 4.1.6 on 2023-02-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0026_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
    ]
